package practicavacas;

/**
 *
 * @author Ludwing_98
 */
public class Inicio extends javax.swing.JFrame {

    public int noestaciones,noaviones,turno=0,turnoDesabordaje,turnoMantenimiento;
    public ColaPasajero cp;
    public ListaAvion la;
    public ListaCircularMaletas lcm;
    public ListaMantenimiento lm;
    NodoAvion avion;
    public void descontarTurnoDesabordaje(){
        turnoDesabordaje=avion.avion.turnosDesabordaje;
        turnoDesabordaje--;
        avion.avion.setTurnosDesabordaje(turnoDesabordaje);
    }
    public void descontarTurnoMantenimiento(){
        turnoMantenimiento= avion.avion.turnosMantenimiento;
        turnoMantenimiento--;
        avion.avion.setTurnosMantenimiento(turnoMantenimiento);
    }
    public Inicio() {
        initComponents();
        pasarTurno.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Consola = new javax.swing.JTextArea();
        noAviones = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        noEstaciones = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comenzar = new javax.swing.JButton();
        pasarTurno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listairport");
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        Consola.setColumns(20);
        Consola.setRows(5);
        jScrollPane1.setViewportView(Consola);

        noAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noAvionesActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad de Aviones");

        jLabel2.setText("No. Estaciones de Mantenimiento");

        comenzar.setText("Comenzar");
        comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarActionPerformed(evt);
            }
        });

        pasarTurno.setText("Pasar Turno");
        pasarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasarTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(noEstaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(noAviones))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(comenzar)
                        .addGap(28, 28, 28)
                        .addComponent(pasarTurno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noAviones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noEstaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comenzar)
                    .addComponent(pasarTurno))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarActionPerformed
        noaviones= Integer.parseInt(noAviones.getText());
        noestaciones= Integer.parseInt(noEstaciones.getText());
        cp= new ColaPasajero();
        la= new ListaAvion();
        lcm= new ListaCircularMaletas();
        lm = new ListaMantenimiento();
        pasarTurno.enable(true);
    }//GEN-LAST:event_comenzarActionPerformed

    private void noAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noAvionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noAvionesActionPerformed
    public void agregarArea(){
        Consola.setText("-------Pasajeros-------\n"+cp.mostrarLista(Consola)+
                "-------Aviones-------\n"+la.mostrarInicio(turno, Consola)+
                "-------Maletas-------\n"+lcm.mostrar(Consola)+"-------Mantenimiento-------\n"+lm.mostrarLista());
    }
    private void pasarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasarTurnoActionPerformed
        turno++;
        System.out.println(""+turno);
        //cp= new ColaPasajero();
        /*la.agregarFinal();
       // la.disminuirTurno();
        //descontarTurnoDesabordaje();
        //la.agregarInicio();
        la.mostrarInicio(turno, Consola);
        cp.agregarFinal();
        cp.agregarFinal();
        cp.mostrarLista(Consola);
        lcm.insertar(turno);
        lcm.insertar(turno);
        lcm.eliminarPrimero();
        la.eliminar(0);
        agregarArea();
        la.disminuirTurno();
        //eliminar();
        //lcm.mostrar(Consola);
        //la.agregarInicio();
        //la.agregarInicio();*/
        agregarPasajeros();
        agregarArea();
    }//GEN-LAST:event_pasarTurnoActionPerformed
    public void agregarPasajeros(){
        la.agregarFinal();
        for (int i = 0; i < la.inicio.avion.pasajeros; i++) {
            cp.agregarFinal();
        }
    }
    /*public void eliminar(){
        if(la.g){
            la.eliminar(0);
        }
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Consola;
    private javax.swing.JButton comenzar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noAviones;
    private javax.swing.JTextField noEstaciones;
    private javax.swing.JButton pasarTurno;
    // End of variables declaration//GEN-END:variables
}
